apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    teir: app
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    teir: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cart
      project: roboshop
      teir: app
  template:
    metadata:
      labels:
        component: cart
        project: roboshop
        teir: app
    spec:
      containers:
      - name: cart
        image: joindevops/cart:v1
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    teir: app
spec:
  selector:
    component: cart
    project: roboshop
    teir: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080